version: "3.6"

networks:
    historic:
        name: historic
services:
    php:
        build: docker/php/dev/api
        container_name: php
        networks:
            - historic
            - default
        user: www-data
        volumes:
            - ./api:/var/www/api/:delegated,rw
            - /etc/timezone:/etc/timezone
            - ./docker/php/dev/api/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./documents:/var/www/documents
        links:
            - db
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "9001:9000"
    nginx:
        image: nginx:1.21-alpine
        ports:
            - ${NGINX_HTTP_PORT}:80
            - ${NGINX_HTTPS_PORT}:80
        networks:
            - historic
            - default
        links:
            - php
            - php-proxy
        volumes:
            - ./api:/var/www/api/
            - ./document-proxy:/var/www/proxy/
            - /etc/timezone:/etc/timezone
            - ./docker/data/api/nginx/log:/var/log/nginx
            - ./docker/config/nginx:/etc/nginx/conf.d
            # - ./documents:/var/www/documents
        restart: always
    db:
        image: postgres:14.3-alpine
        networks:
            - historic
            - default
        ports:
            - ${DB_CUSTOM_PORT}:5432
        volumes:
            - /etc/timezone:/etc/timezone
            - ./docker/data/api/db:/var/lib/postgresql
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
        - '2181:2181'
        environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
        - historic
        - default
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
        - '9092:9092'
        environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CLIENT_USERS=historic
        - KAFKA_CLIENT_PASSWORDS=historic
        volumes:
            - './docker/config/kafka:/opt/bitnami/kafka/config/certs'
        networks:
            - historic
            - default
        depends_on:
            - zookeeper
    php-proxy:
        build: docker/php/dev/proxy
        networks:
            - historic
            - default
        user: www-data
        volumes:
            - ./document-proxy:/var/www/proxy/:delegated,rw
            - /etc/timezone:/etc/timezone
            - ./docker/php/dev/proxy/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./documents:/var/www/documents:delegated,rw
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "9002:9000"
    # nginx-proxy:
    #     image: nginx:1.21-alpine
    #     ports:
    #         - ${NGINX_PROXY_HTTP_PORT}:81
    #         - ${NGINX_PROXY_HTTPS_PORT}:82
    #     networks:
    #         - historic
    #         - default
    #     links:
    #         - php-proxy
    #     volumes:
    #         - ./document-proxy:/var/www/html/
    #         - /etc/timezone:/etc/timezone
    #         - ./docker/data/proxy/nginx/log:/var/log/nginx
    #         - ./docker/config/nginx-proxy:/etc/nginx/conf.d
    #         - ./documents:/var/www/documents
    #     restart: always